### ISSUE TITLE
React-router-bootstrap is not working with react-router 5.0.0

### ISSUE THREAD

**Issue by kris2kris** [react-bootstrap/react-router-bootstrap#250] opened 2019-03-22 14:02 UTC
Since react-router is in version 5.0.0, react-router-bootstrap is not working.

The following error occurred `LinkContainer.js:147 Uncaught TypeError: Cannot read property 'history' of undefined at LinkContainer.render (LinkContainer.js:147)`

More information about this problem can be find here [(https://github.com/ReactTraining/react-router/issues/6630)]

for information :
> @sampsakuronen We have never documented or supported using `this.context.router` directly. That's our private API. I discussed this in [the release notes to 4.4.0-beta.0](https://github.com/ReactTraining/react-router/releases/tag/v4.4.0-beta.0).

**Comment by mxschmitt** [comment] 2019-03-22 15:18
I think #248 fixed that, but we have to publish a new release.
cc @jquense @taion

**Comment by ArnoSaine** [comment] 2019-03-27 11:30
Here's a workaround until #248 is released:
```js
import React from 'react';
import PropTypes from 'prop-types';
import { BrowserRouter, withRouter } from 'react-router-dom';

<BrowserRouter>
  <RouterContextProvider>
    // ...
  </RouterContextProvider>
</BrowserRouter>

const RouterContextProvider = withRouter(
  class extends React.Component {
    static childContextTypes = {
      router: PropTypes.object
    };

    getChildContext() {
      const { children, ...router } = this.props;
      return { router };
    }

    render() {
      return this.props.children;
    }
  }
);
```

**Comment by v12** [comment] 2019-04-04 17:03
This issue is resolved in [v0.25.0](https://github.com/react-bootstrap/react-router-bootstrap/releases/tag/v0.25.0), which is already published to [npm](https://www.npmjs.com/package/react-router-bootstrap).

**Closed by v12** 2019-04-04 17:03 UTC

**Comment by batbayar-su** [comment] 2019-07-14 12:03
Still having this issue in `v0.25.0`

**Comment by v12** [comment] 2019-07-14 18:01
@batbayar-su could you please provide an example that reproduces the problem? Original issue was resolved and you need to elaborate what your setup is to ensure that your issue is the same.

**Comment by batbayar-su** [comment] 2019-07-15 02:56
> Here's a workaround until #248 is released:
> 
> ```js
> import React from 'react';
> import PropTypes from 'prop-types';
> import { BrowserRouter, withRouter } from 'react-router-dom';
> 
> <BrowserRouter>
>   <RouterContextProvider>
>     // ...
>   </RouterContextProvider>
> </BrowserRouter>
> 
> const RouterContextProvider = withRouter(
>   class extends React.Component {
>     static childContextTypes = {
>       router: PropTypes.object
>     };
> 
>     getChildContext() {
>       const { children, ...router } = this.props;
>       return { router };
>     }
> 
>     render() {
>       return this.props.children;
>     }
>   }
> );
> ```

It working with this modification. @ArnoSaine could you explain to me why it is necessary, please?

**Comment by ArnoSaine** [comment] 2019-07-15 10:27
> It worked with this modification. @ArnoSaine could you explain to me why it is necessary, please?

@batbayar-su react-router-bootstrap <0.25 uses `this.context.router` to access React Router context. React Router v5 switched to the current context API and `this.context.router` is not available.

`<RouterContextProvider>` uses the legacy context API to provide router context (`this.context.router`) to its children, so it's possible to use React Router v5 with react-router-bootstrap <0.25.

**Comment by martinduo** [comment] 2019-11-25 03:04
I have this problem using react-router-bootstrap  v0.25.0 and react-router-dom v5.1.2. My environment is from CRA and I do not know how to apply the workaround shown. How and where do I add that workaround? Any example code or instructions? Is there a substitute for react-router-bootstrap I could try?

**Comment by martinduo** [comment] 2019-11-26 15:19
Update to my last above: After stopping work on my project due to this bug, I came back 2 days later and it works with no error. Does this mean it's a timing bug? And if I had restarted at the time it would have gone away?
