### ISSUE TITLE
LinkContainer does not work in router-dom v6

### ISSUE THREAD

**Issue by BlackBird-911** [react-bootstrap/react-router-bootstrap#267] opened 2021-11-09 14:43 UTC
./node_modules/react-router-bootstrap/lib/LinkContainer.js
SyntaxError: E:\pathto project\node_modules\react-router-bootstrap\lib\LinkContainer.js: Support for the experimental syntax 'jsx' isn't currently enabled (68:5):

  66 |
  67 |   return (
> 68 |     <Route
     |     ^
  69 |       path={path}
  70 |       element={<InnerRouteElement />}
  71 |     />
  
  this is the error it shows while compiling and i tried babelrc:true and other solutions, didn't work,
  
  this LinkContainer.js File is from upgrade-react-router branch

**Comment by kyletsang** [comment] 2021-11-18 08:27
Dupe of #266

**Closed by kyletsang** 2021-11-18 08:27 UTC
